<?php

/**
 * @file
 * Examples showing how to use some of the new JavaScript features in Drupal 7.
 */

/**
 * @defgroup islandora_web_annotations Example: JavaScript
 * @ingroup examples
 * @{
 * Examples using Drupal 7's built-in JavaScript.
 */

define('ISLANDORA_WEB_ANNOTATION_VIEW', 'View Web Annotations');
define('ISLANDORA_WEB_ANNOTATION_CREATE', 'Create Web Annotations');
define('ISLANDORA_WEB_ANNOTATION_EDIT_ANY', 'Edit any Web Annotations');
define('ISLANDORA_WEB_ANNOTATION_DELETE_ANY', 'Delete Any Web Annotations');
define('ISLANDORA_WEB_ANNOTATION_EDIT_OWN', 'Edit Own Web Annotations');
define('ISLANDORA_WEB_ANNOTATION_DELETE_OWN', 'Delete Own Web Annotations');

/**
 * Implements hook_theme().
 */
function islandora_web_annotations_theme() {
  return array(
    'my_accordion' => array(
      'template' => 'accordion',
      'variables' => array('title' => NULL),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_web_annotations_menu() {
    $items = array();
    $items['islandora_web_annotations/accordion'] = array(
        'title' => 'JS Test',
        'page callback' => 'islandora_web_annotations_accordion',
        'access callback' => TRUE,
    );
    $items['islandora_web_annotations/create'] = array(
        'title' => 'Create Web Annotation',
        'description' => 'Add a new Web Annotation',
        'page callback' => 'createAnnotation',
        'access callback' => TRUE,
        'file' => 'includes/AnnotationController.php',
        'access arguments' => array(ISLANDORA_WEB_ANNOTATION_CREATE),
        'type' => MENU_CALLBACK,
    );

    $items['islandora_web_annotations/get'] = array(
        'title' => 'Get Web Annotation Container',
        'description' => 'Get Annotation Container',
        'page callback' => 'getAnnotationContainer',
        'access callback' => TRUE,
        'file' => 'includes/AnnotationController.php',
        'access arguments' => array(ISLANDORA_WEB_ANNOTATION_VIEW),
        'type' => MENU_CALLBACK,
    );

    $items['islandora_web_annotations/update'] = array(
        'title' => 'Update Annotation',
        'description' => 'Update Annotation',
        'page callback' => 'updateAnnotation',
        'access callback' => TRUE,
        'file' => 'includes/AnnotationController.php',
        'access arguments' => array(ISLANDORA_WEB_ANNOTATION_EDIT_ANY, ISLANDORA_WEB_ANNOTATION_EDIT_OWN),
        'type' => MENU_CALLBACK,
    );

    $items['islandora_web_annotations/delete'] = array(
        'title' => 'Delete Annotation',
        'description' => 'Delete Annotation',
        'page callback' => 'deleteAnnotation',
        'access callback' => TRUE,
        'file' => 'includes/AnnotationController.php',
        'access arguments' => array(ISLANDORA_WEB_ANNOTATION_DELETE_ANY, ISLANDORA_WEB_ANNOTATION_DELETE_OWN),
        'type' => MENU_CALLBACK,
    );

    $items['islandora_web_annotations/install'] = array(
        'title' => 'Install Annotation Module Objects',
        'description' => 'Install Annotation Module Objects',
        'page callback' => 'installRequiredObjects',
        'access callback' => TRUE,
        'file' => 'includes/AnnotationController.php',
        'type' => MENU_CALLBACK,
    );

    return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_web_annotations_permission() {
    return array(
        ISLANDORA_WEB_ANNOTATION_VIEW => array(
            'title' => t('View web annotations'),
            'description' => t('view web annotations.'),
        ),
        ISLANDORA_WEB_ANNOTATION_CREATE => array(
            'title' => t('Create web annotations'),
            'description' => t('create web annotations'),
        ),
        ISLANDORA_WEB_ANNOTATION_EDIT_ANY => array(
            'title' => t('Edit any web annotations'),
            'description' => t('edit any web annotations'),
        ),
        ISLANDORA_WEB_ANNOTATION_DELETE_ANY => array(
            'title' => t('Delete any web annotations'),
            'description' => t('delete any web annotations'),
        ),
        ISLANDORA_WEB_ANNOTATION_EDIT_OWN => array(
            'title' => t('Edit own web annotations'),
            'description' => t('edit own web annotations'),
        ),
        ISLANDORA_WEB_ANNOTATION_DELETE_OWN => array(
            'title' => t('Delete own web annotations'),
            'description' => t('delete own web annotations'),
        ),
    );
}

/**
 * Send user access related information to js for access control
 */
function islandora_web_annotations_init() {
    $view = user_access(ISLANDORA_WEB_ANNOTATION_VIEW);
    $create = user_access(ISLANDORA_WEB_ANNOTATION_CREATE);
    $edit_any = user_access(ISLANDORA_WEB_ANNOTATION_EDIT_ANY);
    $delete_any = user_access(ISLANDORA_WEB_ANNOTATION_DELETE_ANY);
    $edit_own = user_access(ISLANDORA_WEB_ANNOTATION_EDIT_OWN);
    $delete_own = user_access(ISLANDORA_WEB_ANNOTATION_DELETE_OWN);

    drupal_add_js(array('islandora_web_annotations' => array('view' => $view, 'create'=>$create, 'edit_any'=>$edit_any, 'delete_any'=>$delete_any, 'edit_own'=>$edit_own, 'delete_own'=>$delete_own)), array('type' => 'setting'));
}


/**
 * Demonstrate accordion effect.
 */
function islandora_web_annotations_accordion() {
  $title = t('Click sections to expand or collapse:');
  $build['myelement'] = array(
    '#theme' => 'my_accordion',
    '#title' => $title,
  );
  $build['myelement']['#attached']['library'][] = array('system', 'ui.accordion');
  $build['myelement']['#attached']['js'][] = array('data' => '(function($){$(function() { $("#accordion").accordion(); })})(jQuery);', 'type' => 'inline');
  $output = drupal_render($build);
  return $output;
}
