<?php
/**
 * @file
 * Definition of appnovation_fillout_viewsfield_handler_fillout.
 * KIM PHAM - A WORK IN PROGRESS.
 */

class islandora_web_annotations_handler_htmlrender extends views_handler_field {
    function render($values) {
        watchdog("test", "handler");
        $value = $this->get_value($values);
        return $value;
    }


//    function render($values) {
//        watchdog("test", "handler");
//        $value = $values->{$this->field_alias};
//        return $value;
//
//    }


//        function render($values)
//        {
//            $value = $this->get_value($values);
//            return $this->sanitize_value($value);
//        }
}